apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
    spec:
      containers:
        - image: docker.io/pashacodefresh/pet-store:d6e86b2bb85a7cb8437ed244a29ca99ec2735f06
          name: pet-store
          ports:
            - containerPort: 3001
